### ISSUE TITLE
Curator hangs /healthcheck if zookeeper target is down

### ISSUE THREAD

**Issue by esiqveland** [MeltwaterArchive/dropwizard-extra#28]
Using this config, I am unable to get a response from the /healthcheck url if the zookeeper instance is down

```
# zookeeper curator
curator:
  ensemble:
    hosts:
      - zkdev
    port: 2181
    sessionTimeout: 30 seconds
    namespace: /dev
  maxRetries: 5
  backOffBaseTime: 2 seconds
  compression: gzip
```
